### PR TITLE
Add libdeviceinfo integration into ayatana-indicator-power

### PR DESCRIPTION
**Pull request by muhammad23012009**

### CODE REVIEW

**Comment by sunweaver** [comment]
@muhammad23012009 one minor thing: please make sure there are no merge commits on the PR branch. Thanks.

**Comment by muhammad23012009** [comment]
> @muhammad23012009:
> 
> Can't we put this into the `ENABLE_LOMIRI_FEATURES` ifdef? Or is there a case where we build for Lomiri, but we don't want libdeviceinfo?

I thought that maybe for other distros (i.e, Debian) where Lomiri is packaged with ayatana-indicators but libdeviceinfo is used, it could be excluded to not break dependencies and stuff. But could very well be possible, if libdeviceinfo is packaged for upstream Debian as well.

**Comment by tari01** [comment]
> > @muhammad23012009:
> > Can't we put this into the `ENABLE_LOMIRI_FEATURES` ifdef? Or is there a case where we build for Lomiri, but we don't want libdeviceinfo?
> 
> I thought that maybe for other distros (i.e, Debian) where Lomiri is packaged with ayatana-indicators but libdeviceinfo is not available, it could be excluded to not break dependencies and stuff. But could very well be possible, if libdeviceinfo is packaged for upstream Debian as well.

Let's ask @sunweaver what he thinks: Mike, are you OK with simplifying this by dropping `ENABLE_DEVICEINFO` and using the existing `ENABLE_LOMIRI_FEATURES` to ifdef the new code?

**Comment by sunweaver** [comment]
I'd prefer leaving ENABLE_DEVICEINFO, as it is quite unrelated to Lomiri.

**Review by tari01 — APPROVED** [review]

**Pull request merged**
